CREATE DATABASE IF NOT EXISTS e04dm_inclusion_europe CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE e04dm_inclusion_europe;

CREATE TABLE IF NOT EXISTS inclusion_indicators (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  year SMALLINT NOT NULL,
  dataset JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_year (year)
);
